# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1327, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 100, 141, 101))
        self.label.setStyleSheet("border: 5px solid black;\n"
"font: 75 20pt \"Arial\";")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 100, 141, 101))
        self.label_2.setStyleSheet("border: 5px solid black;\n"
"font: 75 20pt \"Arial\";")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(600, 100, 141, 101))
        self.label_3.setStyleSheet("border: 5px solid black;\n"
"font: 75 20pt \"Arial\";")
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(820, 100, 141, 101))
        self.label_4.setStyleSheet("border: 5px solid black;\n"
"font: 75 20pt \"Arial\";")
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(42, 150, 118, 3))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(120, 70, 3, 82))
        self.line_2.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(120, 70, 203, 3))
        self.line_3.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(340, 70, 3, 82))
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_b1 = QtWidgets.QFrame(self.centralwidget)
        self.line_b1.setGeometry(QtCore.QRect(320, 150, 65, 3))
        self.line_b1.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_b1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_b1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_b1.setObjectName("line_b1")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(540, 40, 3, 111))
        self.line_6.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_b2 = QtWidgets.QFrame(self.centralwidget)
        self.line_b2.setGeometry(QtCore.QRect(540, 150, 65, 3))
        self.line_b2.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_b2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_b2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_b2.setObjectName("line_b2")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(340, 70, 203, 3))
        self.line_8.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(320, 40, 3, 111))
        self.line_9.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(560, 70, 3, 82))
        self.line_10.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(560, 70, 203, 3))
        self.line_11.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_b3 = QtWidgets.QFrame(self.centralwidget)
        self.line_b3.setGeometry(QtCore.QRect(760, 150, 65, 3))
        self.line_b3.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_b3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_b3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_b3.setObjectName("line_b3")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(760, 40, 3, 111))
        self.line_13.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(780, 70, 3, 82))
        self.line_14.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(780, 70, 203, 3))
        self.line_15.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(980, 70, 3, 82))
        self.line_16.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_b4_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_b4_2.setGeometry(QtCore.QRect(980, 150, 65, 3))
        self.line_b4_2.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_b4_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_b4_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_b4_2.setObjectName("line_b4_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 20, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 20, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(710, 20, 101, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 140, 41, 28))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1040, 140, 41, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.time_domain = MplWidget(self.centralwidget)
        self.time_domain.setGeometry(QtCore.QRect(260, 250, 580, 450))
        self.time_domain.setObjectName("time_domain")
        self.frequency_domain = MplWidget(self.centralwidget)
        self.frequency_domain.setGeometry(QtCore.QRect(790, 250, 580, 450))
        self.frequency_domain.setObjectName("frequency_domain")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 240, 241, 451))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_frequency_control = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_frequency_control.setObjectName("lineEdit_frequency_control")
        self.gridLayout.addWidget(self.lineEdit_frequency_control, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_amplitude_sin = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_amplitude_sin.setObjectName("lineEdit_amplitude_sin")
        self.gridLayout.addWidget(self.lineEdit_amplitude_sin, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.lineEdit_frequency_sin = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_frequency_sin.setObjectName("lineEdit_frequency_sin")
        self.gridLayout.addWidget(self.lineEdit_frequency_sin, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 2)
        self.lineEdit_dc_control = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_dc_control.setObjectName("lineEdit_dc_control")
        self.gridLayout.addWidget(self.lineEdit_dc_control, 6, 1, 1, 1)
        self.lineEdit_frequency_filter = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_frequency_filter.setObjectName("lineEdit_frequency_filter")
        self.gridLayout.addWidget(self.lineEdit_frequency_filter, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 2)
        self.pushButton_configure = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_configure.setObjectName("pushButton_configure")
        self.gridLayout.addWidget(self.pushButton_configure, 9, 0, 1, 2)
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(140, 220, 755, 3))
        self.line_18.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(894, 198, 3, 24))
        self.line_19.setStyleSheet("background-color: rgb(0, 0, 0)\n"
"")
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(670, 199, 3, 24))
        self.line_20.setStyleSheet("background-color: rgb(0, 0, 0)\n"
"")
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(450, 199, 3, 24))
        self.line_21.setStyleSheet("background-color: rgb(0, 0, 0)\n"
"")
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(230, 199, 3, 24))
        self.line_22.setStyleSheet("background-color: rgb(0, 0, 0)\n"
"")
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 210, 41, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.checkBox_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_1.setEnabled(False)
        self.checkBox_1.setGeometry(QtCore.QRect(306, 175, 81, 16))
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setGeometry(QtCore.QRect(527, 166, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setGeometry(QtCore.QRect(746, 169, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setGeometry(QtCore.QRect(972, 172, 81, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1327, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "AAF"))
        self.label_2.setText(_translate("MainWindow", "S/H"))
        self.label_3.setText(_translate("MainWindow", "SW"))
        self.label_4.setText(_translate("MainWindow", "RF"))
        self.pushButton_2.setText(_translate("MainWindow", "x1"))
        self.pushButton_3.setText(_translate("MainWindow", "x2"))
        self.pushButton_4.setText(_translate("MainWindow", "x3"))
        self.pushButton_1.setText(_translate("MainWindow", "x0"))
        self.pushButton_5.setText(_translate("MainWindow", "x4"))
        self.groupBox.setTitle(_translate("MainWindow", "Customization"))
        self.label_8.setText(_translate("MainWindow", "Digital Control Signal:"))
        self.label_7.setText(_translate("MainWindow", "Amplitude (V):"))
        self.label_6.setText(_translate("MainWindow", "Frequency (kHz):"))
        self.label_10.setText(_translate("MainWindow", "DC (%)"))
        self.label_9.setText(_translate("MainWindow", "Frequency (kHz):"))
        self.label_12.setText(_translate("MainWindow", "Frequency (kHz):"))
        self.label_11.setText(_translate("MainWindow", "Low Pass Filtter:"))
        self.label_5.setText(_translate("MainWindow", "Analog Signal in:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Sin()"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Cos()"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3/2Sin()"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Sinc()"))
        self.comboBox.setItemText(4, _translate("MainWindow", "AM()"))
        self.pushButton_configure.setText(_translate("MainWindow", "Configure"))
        self.pushButton_6.setText(_translate("MainWindow", "x5"))
        self.checkBox_1.setText(_translate("MainWindow", "Use AAF"))
        self.checkBox_2.setText(_translate("MainWindow", "Use S/H"))
        self.checkBox_3.setText(_translate("MainWindow", "Use SW"))
        self.checkBox_4.setText(_translate("MainWindow", "Use RF"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
